version: "1.0"
info:
  model: int-scaffold
packages:
- name: TechX_User_52Project
  gitServerName: felixgonz
  gitUrl: https://github.com/felixgonz
  gitUsername: felixgonz
  gitBranch: main
- name: CustomerData
  gitServerName: Git_Christian-Kopecki
  gitUrl: https://github.ibm.com/Christian-Kopecki
  gitUsername: Christian-Kopecki
  gitBranch: main
