version: "1.0"
info:
  model: int-scaffold
packages:
- name: TechX_User_52Project
  gitServerName: felixgonz
  gitUrl: https://github.com/felixgonz
  gitUsername: felixgonz
  gitBranch: main
- name: CustomerData
  version: "1.0"
  gitServerName: Git_Christian-Kopecki
  gitUrl: https://github.ibm.com/Christian-Kopecki
  gitUsername: Christian-Kopecki
  gitBranch: main
services:
- serviceName: project.techx_user_52.integrations:shipOrder
  packages:
  - name: TechX_User_52Project
    version: "1.0"
  - name: CustomerData
    version: "1.0"
- serviceName: CustomerData.impl:getCustomerbyID
  packages:
  - name: CustomerData
    version: "1.0"
- serviceName: pub.cache:get
  packages:
  - name: WmPublic
    version: 11.1.0.0.1969
